version: "3.8"
services:
  htdocs:
    image: php:apache
    volumes:
      - "./src/:/var/www/html"
    ports:
      - 8080:80
      - 4433:443
  database:
    image: mysql:latest
    volumes:
      - "./database/:/docker-entrypoint-initdb.d"
    environment:
        - MYSQL_DATABASE=docker_php
        - MYSQL_USER=docker_php
        - MYSQL_PASSWORD=MYSQL_PASSWORD
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
    phpmyadmin:
      image: phpmyadmin:latest
      ports:
          - 8001:80
      environment:
          - PMA_HOST=database
          - PMA_PORT=3306