version: '3.8'
services:
  htdocs:
    image: nginx:stable-alpine
    container_name: laravel_htdocs
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_php
    volumes:
      - ./src/:/var/www/html
    ports:
      - 9000:9000
  database:
    image: mysql:latest
    container_name: laravel_database
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: laravel_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
